USE [master]
GO

/****** Object:  Database [s17guest44]    Script Date: 5/18/2017 9:57:46 PM ******/
CREATE DATABASE [s17guest44]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N's17guest44', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.CSDB440\MSSQL\DATA\s17guest44.mdf' , SIZE = 4160KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N's17guest44_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.CSDB440\MSSQL\DATA\s17guest44_log.ldf' , SIZE = 784KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [s17guest44] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [s17guest44].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [s17guest44] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [s17guest44] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [s17guest44] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [s17guest44] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [s17guest44] SET ARITHABORT OFF 
GO

ALTER DATABASE [s17guest44] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [s17guest44] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [s17guest44] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [s17guest44] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [s17guest44] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [s17guest44] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [s17guest44] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [s17guest44] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [s17guest44] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [s17guest44] SET  ENABLE_BROKER 
GO

ALTER DATABASE [s17guest44] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [s17guest44] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [s17guest44] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [s17guest44] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [s17guest44] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [s17guest44] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [s17guest44] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [s17guest44] SET RECOVERY FULL 
GO

ALTER DATABASE [s17guest44] SET  MULTI_USER 
GO

ALTER DATABASE [s17guest44] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [s17guest44] SET DB_CHAINING OFF 
GO

ALTER DATABASE [s17guest44] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [s17guest44] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [s17guest44] SET  READ_WRITE 
GO

